version: '3.4'

services:
  carapi:
    image: ${DOCKER_REGISTRY}carapi
    build:
      context: .
      dockerfile: CarApi/Dockerfile
  web:
    image: ${DOCKER_REGISTRY}web
    build:
      context: .
      dockerfile: Web/Dockerfile





