version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  carapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
