version: '3.4'

services:
  carapi:
    image: ${DOCKER_REGISTRY}carapi
    ports:
      - 54411:80
    build:
      context: .
      dockerfile: CarApi/Dockerfile
  carclient:
    image: ${DOCKER_REGISTRY}carclient
    environment:
      - CarApiUrl=http://carapi/
    build:
      context: .
      dockerfile: CarClient/Dockerfile